// checkin_device_test.go covers the v0.12.65 check-in device identity fix
// (2026-09-20 final observations, twice reversed
// before being settled): the ug check-in x-device-id must be a fresh random
// 16-digit numeric string — the login hex32 deviceId provably fails claim
// with 9074, reused/deterministic numeric ids degrade over time, and an
// empty value yields 9004. Explicit per-attempt ids thread through
// status→claim→recheck (paired validation params); auto mode generates a
// new id per call. ugBaseHeaders passthrough for NON-checkin ug endpoints
// is pinned separately by TestUgBaseHeadersCapturedFingerprint.
package upstream

import (
	"errors"
	"net/http"
	"regexp"
	"testing"

	"github.com/varcli/cpa-plugins/plugins/trae/auth"
)

func TestNewCheckinDeviceIDShape(t *testing.T) {
	re := regexp.MustCompile(`^[0-9]{16}$`)
	seen := map[string]bool{}
	for i := 0; i < 200; i++ {
		id := NewCheckinDeviceID()
		if !re.MatchString(id) {
			t.Fatalf("NewCheckinDeviceID() = %q, want exactly 16 digits", id)
		}
		seen[id] = true
	}
	// 200 draws from 10^16 space colliding enough to drop below 199 unique
	// is astronomically unlikely — treat as RNG breakage.
	if len(seen) < 199 {
		t.Errorf("device ids repeat across 200 draws: %d unique", len(seen))
	}
}

func TestCheckinStatusClaimPairDeviceID(t *testing.T) {
	// The explicit id must reach BOTH status and claim verbatim: within one
	// attempt they are paired validation params (upstream discipline), and
	// the post-claim recheck uses the same value again.
	var statusDid, claimDid string
	c := testClient(func(r *http.Request) (*http.Response, error) {
		switch r.URL.Path {
		case EpCheckinStatus:
			statusDid = r.Header.Get("X-Device-Id")
			return jsonResp(200, `{"checked_in":false,"did_checked_in":false,"enable":true,"credits":200}`), nil
		case EpCheckinClaim:
			claimDid = r.Header.Get("X-Device-Id")
			return jsonResp(200, `{"code":0,"message":"ok"}`), nil
		}
		return nil, errors.New("unexpected path " + r.URL.Path)
	})
	// Login-bound hex32 must NOT leak into checkin requests even when set.
	a := &auth.Auth{AccessToken: "at", DeviceID: "abcdef0123456789abcdef0123456789"}
	if _, err := c.CheckinStatus(a, "1234567890123456"); err != nil {
		t.Fatal(err)
	}
	if statusDid != "1234567890123456" {
		t.Errorf("status X-Device-Id = %q, want explicit pairing value", statusDid)
	}
	if _, err := c.CheckinClaim(a, "1234567890123456"); err != nil {
		t.Fatal(err)
	}
	if claimDid != "1234567890123456" {
		t.Errorf("claim X-Device-Id = %q, want same paired value", claimDid)
	}
}

func TestCheckinAutoGeneratedDeviceIDIsNumeric(t *testing.T) {
	// No explicit id → fresh 16-digit numeric generated per call. This is the
	// mode panel/management status-only reads take; the login hex32 (or
	// machineId) must never surface here (empirically: claim ✗ 9074).
	var did string
	c := testClient(func(r *http.Request) (*http.Response, error) {
		if r.URL.Path != EpCheckinStatus {
			return nil, errors.New("unexpected path " + r.URL.Path)
		}
		did = r.Header.Get("X-Device-Id")
		return jsonResp(200, `{"checked_in":false,"did_checked_in":false,"enable":true,"credits":200}`), nil
	})
	a := &auth.Auth{AccessToken: "at", DeviceID: "abcdef0123456789abcdef0123456789", MachineID: "abcdef0123456789abcdef0123456789"}
	if _, err := c.CheckinStatus(a); err != nil {
		t.Fatal(err)
	}
	re := regexp.MustCompile(`^[0-9]{16}$`)
	if !re.MatchString(did) {
		t.Errorf("auto X-Device-Id = %q, want fresh 16-digit numeric", did)
	}
}

func TestCheckinDeviceArg(t *testing.T) {
	// Explicit non-empty wins; empty/absent generates fresh numeric.
	if got := checkinDeviceArg([]string{"9999999999999999"}); got != "9999999999999999" {
		t.Errorf("checkinDeviceArg(explicit) = %q", got)
	}
	re := regexp.MustCompile(`^[0-9]{16}$`)
	for _, arg := range [][]string{nil, {""}} {
		if got := checkinDeviceArg(arg); !re.MatchString(got) {
			t.Errorf("checkinDeviceArg(%v) = %q, want generated 16-digit numeric", arg, got)
		}
	}
}
