// checkin_device_test.go covers the check-in device identity contract:
//
//	v0.12.65 (Coding2API matrix): the ug x-device-id must be numeric
//	(8-24 digits; the login hex32 provably fails claim with 9074, empty
//	yields 9004), and an explicit per-attempt id threads through
//	status→claim→recheck as paired validation params.
//
//	v0.12.73 (magpie#808 root cause): 9074 comes from the token carrying no
//	device binding, not the id shape — so the DEFAULT id is the account's
//	stable numeric a.DeviceID (same identity the bound renewal names in
//	DeviceInfo; official guaranteedDeviceId semantics, trae-checkin
//	"固化 on success" model), with fresh-random as the legacy-shape
//	fallback. Explicit ids still win.
package upstream

import (
	"errors"
	"net/http"
	"regexp"
	"testing"

	"github.com/varcli/cpa-plugins/plugins/trae/auth"
)

func TestNewCheckinDeviceIDShape(t *testing.T) {
	re := regexp.MustCompile(`^[0-9]{16}$`)
	seen := map[string]bool{}
	for i := 0; i < 200; i++ {
		id := NewCheckinDeviceID()
		if !re.MatchString(id) {
			t.Fatalf("NewCheckinDeviceID() = %q, want exactly 16 digits", id)
		}
		seen[id] = true
	}
	// 200 draws from 10^16 space colliding enough to drop below 199 unique
	// is astronomically unlikely — treat as RNG breakage.
	if len(seen) < 199 {
		t.Errorf("device ids repeat across 200 draws: %d unique", len(seen))
	}
}

func TestCheckinStatusClaimPairDeviceID(t *testing.T) {
	// The explicit id must reach BOTH status and claim verbatim: within one
	// attempt they are paired validation params (upstream discipline), and
	// the post-claim recheck uses the same value again.
	var statusDid, claimDid string
	c := testClient(func(r *http.Request) (*http.Response, error) {
		switch r.URL.Path {
		case EpCheckinStatus:
			statusDid = r.Header.Get("X-Device-Id")
			return jsonResp(200, `{"checked_in":false,"did_checked_in":false,"enable":true,"credits":200}`), nil
		case EpCheckinClaim:
			claimDid = r.Header.Get("X-Device-Id")
			return jsonResp(200, `{"code":0,"message":"ok"}`), nil
		}
		return nil, errors.New("unexpected path " + r.URL.Path)
	})
	// Login-bound hex32 must NOT leak into checkin requests even when set.
	a := &auth.Auth{AccessToken: "at", DeviceID: "abcdef0123456789abcdef0123456789"}
	if _, err := c.CheckinStatus(a, "1234567890123456"); err != nil {
		t.Fatal(err)
	}
	if statusDid != "1234567890123456" {
		t.Errorf("status X-Device-Id = %q, want explicit pairing value", statusDid)
	}
	if _, err := c.CheckinClaim(a, "1234567890123456"); err != nil {
		t.Fatal(err)
	}
	if claimDid != "1234567890123456" {
		t.Errorf("claim X-Device-Id = %q, want same paired value", claimDid)
	}
}

func TestCheckinAutoGeneratedDeviceIDIsNumeric(t *testing.T) {
	// No explicit id → fresh 16-digit numeric generated per call. This is the
	// mode panel/management status-only reads take; the login hex32 (or
	// machineId) must never surface here (empirically: claim ✗ 9074).
	var did string
	c := testClient(func(r *http.Request) (*http.Response, error) {
		if r.URL.Path != EpCheckinStatus {
			return nil, errors.New("unexpected path " + r.URL.Path)
		}
		did = r.Header.Get("X-Device-Id")
		return jsonResp(200, `{"checked_in":false,"did_checked_in":false,"enable":true,"credits":200}`), nil
	})
	a := &auth.Auth{AccessToken: "at", DeviceID: "abcdef0123456789abcdef0123456789", MachineID: "abcdef0123456789abcdef0123456789"}
	if _, err := c.CheckinStatus(a); err != nil {
		t.Fatal(err)
	}
	re := regexp.MustCompile(`^[0-9]{16}$`)
	if !re.MatchString(did) {
		t.Errorf("auto X-Device-Id = %q, want fresh 16-digit numeric", did)
	}
}

func TestCheckinDeviceArg(t *testing.T) {
	// Explicit non-empty wins; absent takes the account's stable numeric id
	// when it has the official shape, else generates fresh numeric.
	stable := &auth.Auth{DeviceID: "1111222233334444"}
	if got := checkinDeviceArg(stable, []string{"9999999999999999"}); got != "9999999999999999" {
		t.Errorf("checkinDeviceArg(explicit) = %q", got)
	}
	if got := checkinDeviceArg(stable, nil); got != "1111222233334444" {
		t.Errorf("checkinDeviceArg(stable) = %q, want the account's own numeric id", got)
	}
	re := regexp.MustCompile(`^[0-9]{16}$`)
	hex32 := &auth.Auth{DeviceID: "abcdef0123456789abcdef0123456789"}
	for _, tc := range []struct {
		a   *auth.Auth
		arg []string
	}{{hex32, nil}, {stable, []string{""}}, {nil, nil}} {
		if got := checkinDeviceArg(tc.a, tc.arg); !re.MatchString(got) {
			t.Errorf("checkinDeviceArg(%v, %v) = %q, want generated 16-digit numeric", tc.a, tc.arg, got)
		}
	}
}

func TestCheckinStableDeviceIDUsed(t *testing.T) {
	// v0.12.73: an account with a numeric deviceId checkins AS that device —
	// the same identity the bound renewal names in DeviceInfo.DeviceID, which
	// is what lets the server bind-and-match (magpie#808 device-bound-token
	// contract; official client keeps one id per device).
	var did string
	c := testClient(func(r *http.Request) (*http.Response, error) {
		if r.URL.Path != EpCheckinStatus {
			return nil, errors.New("unexpected path " + r.URL.Path)
		}
		did = r.Header.Get("X-Device-Id")
		return jsonResp(200, `{"checked_in":false,"did_checked_in":false,"enable":true,"credits":200}`), nil
	})
	a := &auth.Auth{AccessToken: "at", DeviceID: "7777888899990000"}
	if _, err := c.CheckinStatus(a); err != nil {
		t.Fatal(err)
	}
	if did != "7777888899990000" {
		t.Errorf("status X-Device-Id = %q, want the account's stable id", did)
	}
}

func TestRotateCheckinDevice(t *testing.T) {
	// 9074 rotation mints a fresh 16-digit id in place.
	a := &auth.Auth{DeviceID: "7777888899990000"}
	if !RotateCheckinDevice(a) {
		t.Fatal("RotateCheckinDevice returned false")
	}
	re := regexp.MustCompile(`^[0-9]{16}$`)
	if a.DeviceID == "7777888899990000" || !re.MatchString(a.DeviceID) {
		t.Errorf("rotated DeviceID = %q, want a fresh 16-digit numeric", a.DeviceID)
	}
}
